### ISSUE TITLE
Basic Usages Guide for novice users

### ISSUE THREAD

**Issue by dalarworld** [beam-australia/laravel-docker#1]
It would be nice to put up some basic usages guide on this, actually there is too much information on internet on this topic but few works out of the box. 
I don't see docker-compose.yml ... can you tell me how to use this ?

**Comment by dalarworld** [comment]
Found other repo with good information and I am through with this :)

**Comment by andrewmclagan** [comment]
hey @dalarworld thanks for the contribution. This repo is an internal project we use here at beam. Feel free to use it - although we do not intend to support it externally.
